apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: micro1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DiegoBorja09/micro1
    targetRevision: main
    chart: charts/micro1
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
