apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: LoadBalancer
  selector:
    app: micro1  # o como se llame tu app
  ports:
    - port: 80
      targetPort: 3000  # debe coincidir con el puerto de tu app