name: Publish Helm Chart

on:
  push:
    branches:
      - main

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.12.0'

    - name: Update Helm chart image tag
      run: |
        sed -i "s|tag:.*|tag: \"${{ github.sha }}\"|" charts/micro1/values.yaml

    - name: Bump chart version
      run: |
        VERSION="0.1.${{ github.run_number }}"
        sed -i "s/^version:.*/version: ${VERSION}/" charts/micro1/Chart.yaml

    - name: Package chart
      run: |
        helm package charts/micro1
        mkdir -p repo
        mv micro1-*.tgz repo/

    - name: Update index.yaml
      run: |
        cd repo
        helm repo index . --url https://diegoborja09.github.io/micro1/

    - name: Push to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./repo
        publish_branch: gh-pages
